pipeline {

    agent any

    stages {

        stage('Install Dependencies') {

            steps {

                bat 'python -m pip install -r "Automation/requirements.txt"'
            }
        }

        stage('Clean Previous Reports') {

            steps {

                bat 'if exist "Automation\\reports\\allure-results" rmdir /s /q "Automation\\reports\\allure-results"'

                bat 'mkdir "Automation\\reports\\allure-results"'
            }
        }

        stage('Run API Tests') {

            environment {

                EXECUTION_TYPE = "local"
            }

            steps {

                catchError(
                    buildResult: 'UNSTABLE',
                    stageResult: 'FAILURE'
                ) {

                    bat '''
                    python -m pytest ^
                    "Automation/tests/api" ^
                    --alluredir="Automation/reports/allure-results"
                    '''
                }
            }
        }

        stage('Run E2E Tests') {

            environment {

                EXECUTION_TYPE = "local"
            }

            steps {

                catchError(
                    buildResult: 'UNSTABLE',
                    stageResult: 'FAILURE'
                ) {

                    bat '''
                    python -m pytest ^
                    "Automation/tests/e2e" ^
                    --alluredir="Automation/reports/allure-results"
                    '''
                }
            }
        }

        stage('Run UI Tests') {

            environment {

                EXECUTION_TYPE = "local"
            }

            steps {

                catchError(
                    buildResult: 'UNSTABLE',
                    stageResult: 'FAILURE'
                ) {

                    bat '''
                    python -m pytest ^
                    "Automation/tests/ui" ^
                    --alluredir="Automation/reports/allure-results"
                    '''
                }
            }
        }

        stage('Run AI Tests') {

            environment {

                EXECUTION_TYPE = "local"
            }

            steps {

                catchError(
                    buildResult: 'UNSTABLE',
                    stageResult: 'FAILURE'
                ) {

                    bat '''
                    python -m pytest ^
                    "Automation/tests/ai" ^
                    --alluredir="Automation/reports/allure-results"
                    '''
                }
            }
        }

        stage('Generate Allure Report') {

            steps {

                allure(

                    includeProperties: false,

                    jdk: '',

                    results: [
                        [
                            path: 'Automation/reports/allure-results'
                        ]
                    ]
                )
            }
        }
    }

    post {

        always {

            archiveArtifacts(

                artifacts: 'Automation/reports/screenshots/*.png',

                allowEmptyArchive: true
            )
        }

        success {

            echo 'Pipeline executed successfully.'
        }

        unstable {

            echo 'Some test cases failed. Build marked as UNSTABLE.'
        }

        failure {

            echo 'Pipeline execution failed.'
        }
    }
}